### ISSUE TITLE
Compiles successfully, but device gets stuck in boot loop after sideload?

### ISSUE THREAD

**Issue by k1rak1ra** [sony-sm8550/android_device_sony_sm8550-common#2]
Hey! I'm not sure if I'm doing something wrong or not, but I've been unable to get an image compiled from these sources to boot successfully on my DQ72

**What I did**
1. I set up a fresh build environment following the guide at at [https://wiki.lineageos.org/devices/kenzo/build/](https://wiki.lineageos.org/devices/kenzo/build/) until the step _Prepare the device-specific code_. I am building on Fedora 6.7.5-200.fc39.x86_64 with all required build dependencies installed.
2. I made a file at **.repo/local_manifests/pdx234.xml** with the following contents: [https://gist.github.com/k1rak1ra/175036ae77a3410ac8e439c25b82a45b](https://gist.github.com/k1rak1ra/175036ae77a3410ac8e439c25b82a45b)
3. I ran `source build/envsetup.sh`, `breakfast pdx234`, `croot`, and then `brunch pdx234`. Compilation was successful
4. I flashed the generated boot, recovery, dtbo, and vendor_boot images using fastboot
5. I booted into Lineage recovery successfully, factory reset, and then adb sideloaded the generated lineage-21.0-xxxxxxx-UNOFFICIAL-pdx234.zip file
6. Upon rebooting my device, it gets stuck in a bootloop, and I need to hold down pwr+voldown in order to exit the bootloop

Sadly, I don't have a UART adapter for my phone, so I am unable to collect debug info from the boot process. But since this is my first time building Lineage from source, I'm curious if I did something wrong
Is the sony-sm8550/android_kernel_sony_sm8550 kernel too old to work with the latest Lineage sources?
Have the maintainers in this github org been able to generate a successful build from the sources in this org + the latest Lineage sources?
Is there anymore more I can do to debug the boot issue apart from connecting UART?

Thanks in advance for your help

**Comment by hellobbn** [comment]
When you say it is a boot loop, does it stuck on the Sony logo or does it shutdown?

**Comment by hellobbn** [comment]
Please merge https://review.lineageos.org/q/topic:%22DISPLAY.LA.3.0.r1-10700-KAILUA.0%22 to hardware/qcom-caf/sm8550/display if it is the former case.

**Comment by k1rak1ra** [comment]
Thank you so much, that fixed the problem, it boots successfully now!
